esphome:
  name: livingroom_switch
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "nana's home"
  password: "871245112312"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Livingroom Switch"
    password: "iBwXjW95YvwQ"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "870102"

ota:
  password: "870102"
  
# Individual outputs

output:
  - platform: gpio
    pin: GPIO5
    id: relay1
    
  - platform: gpio
    pin: GPIO4
    id: relay2
    
  - platform: gpio
    pin: GPIO0
    id: relay3
    
  - platform: gpio
    pin: GPIO16
    id: relay4
light:
  - platform: binary
    name: "light1"
    id: ktd
    output: relay1  
    
  - platform: binary
    name: "light2"
    id: ktsd
    output: relay2
    
  - platform: binary
    name: "light3"
    id: gdsd
    output: relay3

  - platform: binary
    name: "light4"
    id: gddd
    output: relay4
binary_sensor:
  - platform: gpio
    pin: 
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: True
    name: "light1状态"
    on_press:
      then:
        - light.toggle: ktd
    on_release:
      then:
        - light.toggle: ktd
        
  - platform: gpio
    pin: 
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    name: "light2状态"
    on_press:
      then:
        - light.toggle: ktsd
    on_release:
      then:
        - light.toggle: ktsd
        
  - platform: gpio
    pin: 
      number: GPIO14
      mode: INPUT_PULLUP
      inverted: True
    name: "light3状态"
    on_press:
      then:
        - light.toggle: gdsd
    on_release:
      then:
        - light.toggle: gdsd
        
  - platform: gpio
    pin: 
      number: GPIO3
      mode: INPUT_PULLUP
      inverted: True
    name: "light4状态"
    on_press:
      then:
        - light.toggle: gddd
    on_release:
      then:
        - light.toggle: gddd
